/* Define as permissões de leitura e escrita da base. */

------------
-- SYSDBA --
------------

--Procedures
GRANT EXECUTE ON PROCEDURE PR_ADMDEL_SERVIDOR_CAPP TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_ADMUP_SERVIDOR_CAPP TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_ARQUIVOS_LOJA_PENDENTES TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_CADASTRA_DISPOSITIVO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_CANCELA_PEDIDO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_CANCELA_PEDIDO_ADM TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_CANCELA_PEDIDO_WEB TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_CONFIRMA_FALHA_PEDIDO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_CONFIRMA_PEDIDO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_CONFIRMA_PEDIDO_WEB TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_CONFIRMA_RECEBIMENTO_CANC TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_CONFIRMA_RECEBIMENTO_PEDIDO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_CREDITO_RECEBIDO_LOJA TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_FIX_LOJA_ANTIGO_CAPP_TMP TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_FORMAT_DECIMAL_PRECO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_FORMAT_GRUPO_MODULO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_FORMAT_HORARIO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_FORMAT_MODULO_DESCRICAO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_FORMAT_MONEY_REAL TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_GET_GRUPO_MAIOR_STRING TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_GET_GRUPO_MODULO_ID TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_GET_NEXT_GRUPO_MODULO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_MIGRA_DISPOSITIVO_SERVER TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_MIGRA_LOJA_SERVER TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_PREPARA_LISTA_CIDADES TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_PREPARA_LISTA_LOJAS TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_PREPARA_LISTA_LOJAS_NOVO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_APP_TOKEN_FCM TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_APP_VERSAO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_ARQUIVOS_USO_LOJA TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_ARQUIVO_DISPONIVEL TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_DOWNLOAD_ARQUIVO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_ENDERECO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_EXCLUSAO_ARQUIVO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_IMAGEM_LOJA TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_LOGADO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_LOJA TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_LOJA_ARQUIVO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_LOJA_COMPLETO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_B_1 TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_B_2 TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_B_3 TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_C_1 TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_P_1 TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_P_2 TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_P_3 TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_P_4 TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_P_5 TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_P_6 TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_RESTART TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_NOTI_START TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_PEDIDO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_PEDIDO_NOVO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_PEDIDO_REST TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_REQUISICAO_FCM TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_USUARIO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_USUARIO_NOVO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_RETORNA_BONUS_USUARIO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_RETORNA_CADASTRO_DISPOSITIVO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_RETORNA_CADASTRO_MONITOR TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_RETORNA_IMAGEM_COMUM TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_RETORNA_IMAGENS_FALTANTES TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_SPLIT_STRING TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_SYNC_DISPOSITIVO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_SYNC_LOJA TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_UP_DEV_INFOS_EXTRA TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_UP_STATUS_NOTIFS TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_VALIDA_LOGIN TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_VALIDA_LOGIN_LOJA_WEB TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_VALIDA_LOGIN_MONITORAMENTO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_VALIDA_LOGIN_MONITORA_NOVO TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_VALOR_PEDIDO_ITEM TO SYSDBA;
GRANT EXECUTE ON PROCEDURE PR_VALOR_TOTAL_PEDIDO TO SYSDBA;

-- Tabelas
GRANT ALL ON ARQUIVO_DISPONIVEL TO SYSDBA;
GRANT ALL ON ARQUIVO_DOWNLOAD TO SYSDBA;
GRANT ALL ON BAIRRO TO SYSDBA;
GRANT ALL ON CATEGORIA TO SYSDBA;
GRANT ALL ON CIDADE TO SYSDBA;
GRANT ALL ON CIDADE_ARQUIVO_DISPONIVEL TO SYSDBA;
GRANT ALL ON CONF_EGULA_WEB TO SYSDBA;
GRANT ALL ON DISPOSITIVO TO SYSDBA;
GRANT ALL ON DISPOSITIVO_ACAO TO SYSDBA;
GRANT ALL ON DISPOSITIVO_APP_TOKEN_FCM TO SYSDBA;
GRANT ALL ON DISPOSITIVO_APP_VERSAO TO SYSDBA;
GRANT ALL ON DISPOSITIVO_ARQUIVO_DISPONIVEL TO SYSDBA;
GRANT ALL ON DISPOSITIVO_LOJA_SERVIDOR TO SYSDBA;
GRANT ALL ON DISPOSITIVO_SERVIDOR_DEFAULT TO SYSDBA;
GRANT ALL ON ENDERECO TO SYSDBA;
GRANT ALL ON ESTADO TO SYSDBA;
GRANT ALL ON FORMA_ENTREGA TO SYSDBA;
GRANT ALL ON FORMA_PAGAMENTO TO SYSDBA;
GRANT ALL ON GRUPO_PRODUTO TO SYSDBA;
GRANT ALL ON HORARIO_ATENDIMENTO TO SYSDBA;
GRANT ALL ON LISTA_NEGRA TO SYSDBA;
GRANT ALL ON LOJA TO SYSDBA;
GRANT ALL ON LOJA_ARQUIVO_DISPONIVEL TO SYSDBA;
GRANT ALL ON LOJA_BONUS_CONF TO SYSDBA;
GRANT ALL ON LOJA_CATEGORIA TO SYSDBA;
GRANT ALL ON LOJA_CREDITO TO SYSDBA;
GRANT ALL ON LOJA_ENDERECO TO SYSDBA;
GRANT ALL ON LOJA_OPERADOR_ACESSO TO SYSDBA;
GRANT ALL ON LOJA_SERVIDOR_DEFAULT TO SYSDBA;
GRANT ALL ON MONITOR_SC TO SYSDBA;
GRANT ALL ON MONITOR_SC_ACAO TO SYSDBA;
GRANT ALL ON NOTIFICACAO TO SYSDBA;
GRANT ALL ON NOTIFICACAO_DISPOSITIVO TO SYSDBA;
GRANT ALL ON NOTIFICACAO_USUARIO TO SYSDBA;
GRANT ALL ON OPCIONAL_PRODUTO TO SYSDBA;
GRANT ALL ON OPCIONAL_PRODUTO_DISPONIVEL TO SYSDBA;
GRANT ALL ON OPERADOR TO SYSDBA;
GRANT ALL ON OP_PROD_VALOR_TAMANHO_PROD TO SYSDBA;
GRANT ALL ON PAIS TO SYSDBA;
GRANT ALL ON PEDIDO TO SYSDBA;
GRANT ALL ON PEDIDO_ITEM TO SYSDBA;
GRANT ALL ON PEDIDO_ITEM_INGR TO SYSDBA;
GRANT ALL ON PEDIDO_ITEM_OPCIONAL_PROD TO SYSDBA;
GRANT ALL ON PEDIDO_ITEM_SABOR_INGR2 TO SYSDBA;
GRANT ALL ON PEDIDO_ITEM_SABOR_PROD2 TO SYSDBA;
GRANT ALL ON PRODUTO TO SYSDBA;
GRANT ALL ON PRODUTO_INGREDIENTE TO SYSDBA;
GRANT ALL ON SABOR TO SYSDBA;
GRANT ALL ON SABOR_PRODUTO_DISPONIVEL TO SYSDBA;
GRANT ALL ON SABOR_PRODUTO_INGREDIENTE TO SYSDBA;
GRANT ALL ON SERVIDOR TO SYSDBA;
GRANT ALL ON TAMANHO_PRODUTO TO SYSDBA;
GRANT ALL ON TAMANHO_PRODUTO_DISPONIVEL TO SYSDBA;
GRANT ALL ON TELEFONE TO SYSDBA;
GRANT ALL ON TPD_SPD_VALOR TO SYSDBA;
GRANT ALL ON UNIDADE_MEDIDA TO SYSDBA;
GRANT ALL ON USO_API_EXTERNA TO SYSDBA;
GRANT ALL ON USO_API_EXTERNA_TOKEN_FCM TO SYSDBA;
GRANT ALL ON USUARIO TO SYSDBA;
GRANT ALL ON USUARIO_ENDERECO TO SYSDBA;
GRANT ALL ON USUARIO_LOGADO TO SYSDBA;
GRANT ALL ON USUARIO_TELEFONE TO SYSDBA;

-- Views
GRANT ALL ON VWR_DISPOSITIVOS TO SYSDBA;
GRANT ALL ON VWR_GERENCIAL_EGULA TO SYSDBA;
GRANT ALL ON VWR_LOJA_SALDOS_PEDIDOS TO SYSDBA;
GRANT ALL ON VWR_PEDIDOS_HISTORICO_LOJA TO SYSDBA;
GRANT ALL ON VWR_PEDIDOS_MONITORAMENTO TO SYSDBA;
GRANT ALL ON VWR_USUARIOS TO SYSDBA;
GRANT ALL ON VWR_USUARIOS_NOVO TO SYSDBA;
GRANT ALL ON VWR_USUARIOS_SIMPLES TO SYSDBA;
GRANT ALL ON VW_ARQUIVOS_DISPONIVEIS_DEV TO SYSDBA;
GRANT ALL ON VW_ARQUIVO_INICIAL_DISPONIVEL TO SYSDBA;
GRANT ALL ON VW_ARQUIVO_LOJA_DISPONIVEL TO SYSDBA;
GRANT ALL ON VW_ARQUIVO_LOJA_FORCADO TO SYSDBA;
GRANT ALL ON VW_ARQUIVO_LOJA_PENDENTE_EXCLUS TO SYSDBA;
GRANT ALL ON VW_BONUS_LIVRE_USUARIO TO SYSDBA;
GRANT ALL ON VW_HOST_DIRECIONADO_DISPOSITIVO TO SYSDBA;
GRANT ALL ON VW_HOST_DIRECIONADO_LOJA TO SYSDBA;
GRANT ALL ON VW_HOST_DIRECIONADO_LOJA_DEV TO SYSDBA;
GRANT ALL ON VW_INFOS_CIDADE TO SYSDBA;
GRANT ALL ON VW_INFOS_CREDITO_LOJA_PENDENTE TO SYSDBA;
GRANT ALL ON VW_INFOS_DISPOSITIVO TO SYSDBA;
GRANT ALL ON VW_INFOS_ENDERECO TO SYSDBA;
GRANT ALL ON VW_INFOS_LOJA TO SYSDBA;
GRANT ALL ON VW_INFOS_LOJA_FIREBASE TO SYSDBA;
GRANT ALL ON VW_INFOS_NOTI_DISPOSITIVO TO SYSDBA;
GRANT ALL ON VW_INFOS_NOTI_USUARIO TO SYSDBA;
GRANT ALL ON VW_INFOS_PEDIDOS_CANCELAVEIS TO SYSDBA;
GRANT ALL ON VW_INFOS_PEDIDOS_ITENS_MONITO TO SYSDBA;
GRANT ALL ON VW_INFOS_PEDIDOS_ITENS_SC TO SYSDBA;
GRANT ALL ON VW_INFOS_PEDIDOS_PENDENTES TO SYSDBA;
GRANT ALL ON VW_INFOS_PEDIDOS_PENDENTES_CANC TO SYSDBA;
GRANT ALL ON VW_INFOS_PEDIDOS_PENDENTES_NOVO TO SYSDBA;
GRANT ALL ON VW_INFOS_PEDIDOS_PENDENTES_OLD TO SYSDBA;
GRANT ALL ON VW_INFOS_PEDIDO_DETALHADO TO SYSDBA;
GRANT ALL ON VW_INFOS_PEDIDO_DETA_PEND_LOJA TO SYSDBA;
GRANT ALL ON VW_INFOS_PEDIDO_ITEM_DETALHADO TO SYSDBA;
GRANT ALL ON VW_INFOS_USUARIO TO SYSDBA;
GRANT ALL ON VW_INFOS_USUARIO_ENDERECO TO SYSDBA;
GRANT ALL ON VW_INFOS_USUARIO_TELEFONE TO SYSDBA;
GRANT ALL ON VW_LOJA_NOVO_FORMATO_FX TO SYSDBA;
GRANT ALL ON VW_QTDE_PEDIDO_DEV_LOJA TO SYSDBA;
GRANT ALL ON VW_USUARIO_LOGADO TO SYSDBA;
GRANT ALL ON VW_USUARIO_MONITORAMENTO TO SYSDBA;
GRANT ALL ON VW_USUARIO_ULTIMO_DISPO_LOGADO TO SYSDBA;


-------------------
-- MONITORAMENTO --
-------------------

--Procedures
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_ENDERECO TO MONITORAMENTO;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_IMAGEM_LOJA TO MONITORAMENTO;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_LOJA_ARQUIVO TO MONITORAMENTO;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_LOJA_COMPLETO TO MONITORAMENTO;
GRANT EXECUTE ON PROCEDURE PR_VALIDA_LOGIN_MONITORAMENTO TO MONITORAMENTO;
GRANT EXECUTE ON PROCEDURE PR_VALIDA_LOGIN_MONITORA_NOVO TO MONITORAMENTO;
GRANT EXECUTE ON PROCEDURE PR_VALOR_PEDIDO_ITEM TO MONITORAMENTO;

-- Tabelas
GRANT ALL ON ARQUIVO_DISPONIVEL TO MONITORAMENTO;
GRANT ALL ON BAIRRO TO MONITORAMENTO;
GRANT ALL ON CIDADE TO MONITORAMENTO;
GRANT ALL ON CONF_EGULA_WEB TO MONITORAMENTO;
GRANT ALL ON ENDERECO TO MONITORAMENTO;
GRANT ALL ON ESTADO TO MONITORAMENTO;
GRANT ALL ON LISTA_NEGRA TO MONITORAMENTO;
GRANT ALL ON LOJA TO MONITORAMENTO;
GRANT ALL ON LOJA_ARQUIVO_DISPONIVEL TO MONITORAMENTO;
GRANT ALL ON LOJA_BONUS_CONF TO MONITORAMENTO;
GRANT ALL ON LOJA_CREDITO TO MONITORAMENTO;
GRANT ALL ON LOJA_ENDERECO TO MONITORAMENTO;
GRANT ALL ON LOJA_OPERADOR_ACESSO TO MONITORAMENTO;
GRANT ALL ON OPERADOR TO MONITORAMENTO;
GRANT ALL ON PAIS TO MONITORAMENTO;
GRANT SELECT ON PEDIDO TO MONITORAMENTO;
GRANT SELECT ON PEDIDO_ITEM TO MONITORAMENTO;
GRANT SELECT ON PEDIDO_ITEM_INGR TO MONITORAMENTO;
GRANT SELECT ON PEDIDO_ITEM_OPCIONAL_PROD TO MONITORAMENTO;
GRANT ALL ON PEDIDO_ITEM_SABOR_INGR2 TO MONITORAMENTO;
GRANT ALL ON PEDIDO_ITEM_SABOR_PROD2 TO MONITORAMENTO;
GRANT ALL ON UNIDADE_MEDIDA TO MONITORAMENTO;
GRANT ALL ON USUARIO TO MONITORAMENTO;

-- Views
GRANT SELECT ON USUARIO TO MONITORAMENTO;
GRANT SELECT ON VWR_PEDIDOS_MONITORAMENTO TO MONITORAMENTO;
GRANT SELECT ON VWR_USUARIOS_NOVO TO MONITORAMENTO;
GRANT SELECT ON VWR_USUARIOS_SIMPLES TO MONITORAMENTO;
GRANT SELECT ON VW_INFOS_LOJA TO MONITORAMENTO;
GRANT SELECT ON VW_INFOS_PEDIDO_DETALHADO TO MONITORAMENTO;
GRANT SELECT ON VW_INFOS_PEDIDO_ITEM_DETALHADO TO MONITORAMENTO;
GRANT SELECT ON VW_LOJA_NOVO_FORMATO_FX TO MONITORAMENTO;
GRANT SELECT ON VW_USUARIO_MONITORAMENTO TO MONITORAMENTO;


--------------
-- EGULAWEB --
--------------

--Procedures
GRANT EXECUTE ON PROCEDURE PR_CANCELA_PEDIDO_WEB TO EGULAWEB;
GRANT EXECUTE ON PROCEDURE PR_CONFIRMA_PEDIDO_WEB TO EGULAWEB;
GRANT EXECUTE ON PROCEDURE PR_FORMAT_GRUPO_MODULO TO EGULAWEB;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_ENDERECO TO EGULAWEB;
GRANT EXECUTE ON PROCEDURE PR_REGISTRA_IMAGEM_LOJA TO EGULAWEB;
GRANT EXECUTE ON PROCEDURE PR_VALIDA_LOGIN_LOJA_WEB TO EGULAWEB;
GRANT EXECUTE ON PROCEDURE PR_VALOR_PEDIDO_CLIENTE_ITEM TO EGULAWEB;
GRANT EXECUTE ON PROCEDURE PR_VALOR_PEDIDO_ITEM TO EGULAWEB;
GRANT EXECUTE ON PROCEDURE PR_VALOR_TOTAL_PEDIDO_CLIENTE TO EGULAWEB;

-- Tabelas
GRANT ALL ON ARQUIVO_DISPONIVEL TO EGULAWEB;
GRANT ALL ON BAIRRO TO EGULAWEB;
GRANT ALL ON CIDADE TO EGULAWEB;
GRANT ALL ON CLIENTE TO EGULAWEB;
GRANT ALL ON CLIENTE_ENDERECO TO EGULAWEB;
GRANT ALL ON DISTANCIA_ENTREGA TO EGULAWEB;
GRANT ALL ON ENDERECO TO EGULAWEB;
GRANT ALL ON ESTADO TO EGULAWEB;
GRANT ALL ON FORMA_ENTREGA TO EGULAWEB;
GRANT ALL ON FORMA_PAGAMENTO TO EGULAWEB;
GRANT ALL ON GRUPO_PRODUTO TO EGULAWEB;
GRANT ALL ON HORARIO_ATENDIMENTO TO EGULAWEB;
GRANT ALL ON LOJA TO EGULAWEB;
GRANT ALL ON LOJA_ARQUIVO_DISPONIVEL TO EGULAWEB;
GRANT SELECT ON LOJA_OPERADOR_ACESSO TO EGULAWEB;
GRANT ALL ON MONITOR_SC_ACAO TO EGULAWEB;
GRANT ALL ON OPCIONAL_PRODUTO TO EGULAWEB;
GRANT ALL ON OPCIONAL_PRODUTO_DISPONIVEL TO EGULAWEB;
GRANT SELECT ON OPERADOR TO EGULAWEB;
GRANT ALL ON OP_PROD_VALOR_TAMANHO_PROD TO EGULAWEB;
GRANT ALL ON PAIS TO EGULAWEB;
GRANT ALL ON PEDIDO TO EGULAWEB;
GRANT ALL ON PEDIDO_CLIENTE TO EGULAWEB;
GRANT ALL ON PEDIDO_CLIENTE_ITEM TO EGULAWEB;
GRANT ALL ON PEDIDO_CLIENTE_ITEM_INGR TO EGULAWEB;
GRANT ALL ON PEDIDO_CLIENTE_ITEM_OPC TO EGULAWEB;
GRANT ALL ON PEDIDO_CLIENTE_ITEM_SABOR TO EGULAWEB;
GRANT ALL ON PEDIDO_CLIENTE_ITEM_SAB_INGRE TO EGULAWEB;
GRANT SELECT ON PEDIDO_ITEM_INGR TO EGULAWEB;
GRANT SELECT ON PEDIDO_ITEM TO EGULAWEB;
GRANT SELECT ON PEDIDO_ITEM_OPCIONAL_PROD TO EGULAWEB;
GRANT ALL ON PEDIDO_ITEM_SABOR_INGR2 TO EGULAWEB;
GRANT ALL ON PEDIDO_ITEM_SABOR_PROD2 TO EGULAWEB;
GRANT ALL ON PRODUTO TO EGULAWEB;
GRANT ALL ON PRODUTO_INGREDIENTE TO EGULAWEB;
GRANT ALL ON SABOR TO EGULAWEB;
GRANT ALL ON SABOR_PRODUTO_DISPONIVEL TO EGULAWEB;
GRANT ALL ON SABOR_PRODUTO_INGREDIENTE TO EGULAWEB;
GRANT ALL ON TAMANHO_PRODUTO TO EGULAWEB;
GRANT ALL ON TAMANHO_PRODUTO_DISPONIVEL TO EGULAWEB;
GRANT ALL ON TELEFONE TO EGULAWEB;
GRANT ALL ON TPD_SPD_VALOR TO EGULAWEB;
GRANT SELECT ON UNIDADE_MEDIDA TO EGULAWEB;
GRANT ALL ON LOJA_CONFIG_EGULA_WEB TO EGULAWEB;
GRANT ALL ON MESA_ABERTA TO EGULAWEB;
GRANT ALL ON MESA_PEDIDO TO EGULAWEB;
GRANT ALL ON MESA_FECHAMENTO TO EGULAWEB;
GRANT ALL ON MESA_FECHAMENTO_PARCIAL_ITEM TO EGULAWEB;
GRANT ALL ON USUARIO TO EGULAWEB;
GRANT ALL ON USUARIO_BLOQUEADO TO EGULAWEB;

-- Views
GRANT ALL ON VWR_PEDIDOS_HISTORICO_LOJA TO EGULAWEB;
GRANT SELECT ON VW_INFOS_ENDERECO TO EGULAWEB;
GRANT SELECT ON VW_INFOS_PEDIDO_DETA_PEND_LOJA TO EGULAWEB;
GRANT ALL ON VW_INFOS_PEDIDO_DETALHADO TO EGULAWEB;
GRANT SELECT ON VW_INFOS_PEDIDO_ITEM_DETALHADO TO EGULAWEB;
GRANT SELECT ON VW_LOJA_NOVO_FORMATO_FX TO EGULAWEB;
GRANT ALL ON VW_INFOS_LOJA TO EGULAWEB;
